#\u670D\u52A1\u7AEF\u53E3
server.port=2026
spring.main.lazy-initialization=true

#\u6570\u636E\u6E90
spring.datasource.url=jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;MODE=PostgreSQL
spring.datasource.username=sa

spring.sql.init.schema-locations=classpath:sql/init.sql
